### ISSUE TITLE
Move migration files from migrations_django to its original place

### ISSUE THREAD

**Issue by saeedsq** [divio/djangocms-googlemap#21]
According to django 1.7 inclusion of migration module:
Please change
1) migrations_django to migrations
2) migrations to south_migrations

**Comment by spookylukey** [comment]
The bug here (and with other plugins like -file, -picture, -googlemap, -snippet, -teaser and -video) means that typically upgrading a django-cms project to Django 1.7 fails, and requires custom MIGRATION_MODULES and lots of debugging. Django 3.1 has been released a good while ago now, so the README is quite misleading.

**Comment by FinalAngel** [comment]
fixed
