### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by sedrubal** [divio/djangocms-googlemap#27]
Are you planning or do you want to also provide a plugin for OpenStreetMap? As django cms is used by many opensource projects I'm sure there will be many users of this OSM Plugin.

**Comment by FinalAngel** [comment]
hello @sedrubal, you could technically implement openstreetmap into this plugin and "misuse" the settings. Other than that we'd welcome addon contributions from the community :)

**Comment by bittner** [comment]
I'm interested in alternatives to Google Maps, too. :+1: 

This should include OSM, but may not be limited to it. Other map providers (that could be offered as "map style" or simply "map provider" in some "Advanced Settings", maybe), most if not all of them use OSM data anyway, could be:

- [HERE maps](https://wego.here.com/)
- [MapQuest](https://www.mapquest.com/)
- [ViaMichelin](https://www.viamichelin.com/)
- etc.

For easier maintenance (of the websites created using django CMS) I'd love to see this as an option to this plugin though, rather than having another plugin that would have to be added to `INSTALLED_APPS`.

Alternatives to Google Maps would also make the requirement to specify their API key obsolete (see #40).

**Comment by bittner** [comment]
Could we reopen this issue?

**Comment by FinalAngel** [comment]
@bittner this is a specific plugin for googlemaps, hence the name djangocms-googlemap. For your purpose you'd need to create something like djangocms-maps. I'd love to see a community contribution for such a package :)

**Comment by bittner** [comment]
Okay, let's get it fixed that way.

**Comment by bittner** [comment]
Say hello to [djangocms-maps](https://pypi.python.org/pypi/djangocms-maps), released on PyPI today!   :birthday: :tada:

Supports several map providers and ships **Mapbox OpenStreetMaps** as a default.

**Comment by FinalAngel** [comment]
awesome work @bittner ! You're welcome to add it to the django CMS Marketplace: marketplace.django-cms.org

**Comment by bittner** [comment]
Thanks for the hint, @FinalAngel! - Done.

In the meantime I've released [version 0.6.0](https://pypi.python.org/pypi/djangocms-maps), which also ships **HERE WeGo** and **Bing Maps**.
