### ISSUE TITLE
Zoom level ignored

### ISSUE THREAD

**Issue by tmark-work** [divio/djangocms-googlemap#73]
Tried to set different values, but plugin always sets maximum zoom.
Few months ago everything was ok.
![gmap](https://user-images.githubusercontent.com/19544729/36986862-c3e6f3ae-20bc-11e8-9476-50f970ad6f17.png)

**Comment by ptitmouton** [comment]
I'm having the same problem since a few weeks. Installation has not changed. Seems the google-map-constructor ist correctly being called, but something alters the zoom level.
![djangocmsgooglemaps-zoom](https://user-images.githubusercontent.com/1842883/37038030-f7a35862-2153-11e8-8c71-427619ced76b.gif)
Any idea where this could come from?

**Comment by tmark-work** [comment]
it overrides somehow after calling update function and especially this.map.fitBounds(this.bounds);

**Comment by treavis** [comment]
Commenting line 169 of djangocms.googlemap.js seems to do the trick. ``// this.map.fitBounds(this.bounds);`` .  More written [here](https://stackoverflow.com/questions/29875865/setting-zoom-level-doesnt-work-on-google-map) . Didn't have time to find out why this function breaks zoom functionality, but everything seems to work fine after commenting that line..

**Comment by tmark-work** [comment]
Tried commenting for the quick fix, but found another possible solution at your link.

#74

**Comment by treavis** [comment]
Let's hope that works well. As for the comment method, i didn't find anything wrong, but if you have multiple markers it might not work (i'm guessing).

**Comment by evildmp** [comment]
I think that when you have markers, it zooms in on them and ignores zoom settings.

This is fine when you have several, such as in https://na.pycon.org/en/2018/, but is not so good when you only have one or they are very close together.

A solution could be to have an "automatic" zoom setting that works as it does now, but otherwise the explicit zoom setting takes precedence.

**Comment by vxsx** [comment]
I did some digging and found out that this only happens if the markers have latitude / longitude set directly. This happens because if the lat/lon are available the marker will be added immediately after map initialization and the following callback will be run before marker is actually added to a map because of other "bounds_changed" event, not the one triggered by the following `fitBounds` call:

https://github.com/divio/djangocms-googlemap/blob/e86fe66f52199b4a32fbd43205527c3ef2522c3e/djangocms_googlemap/static/djangocms_googlemap/js/djangocms.googlemap.js#L163-L169

In case geolocation is used - there is an api call and some waiting time - so the event does correctly happen after the map actually renders

https://github.com/divio/djangocms-googlemap/pull/75 fixes the issue by waiting till the first idle event before adding markers (it happens when map initialized, but before tiles are loaded)
